# Generated by Django 6.0.2 on 2026-03-01 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reciter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('name_arabic', models.CharField(blank=True, default='', max_length=200, verbose_name='Имя (арабский)')),
                ('identifier', models.CharField(max_length=100, unique=True, verbose_name='Идентификатор')),
                ('style', models.CharField(blank=True, default='', max_length=100, verbose_name='Стиль чтения')),
                ('audio_base_url', models.URLField(verbose_name='Базовый URL аудио')),
            ],
            options={
                'verbose_name': 'Чтец',
                'verbose_name_plural': 'Чтецы',
            },
        ),
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Номер суры')),
                ('name_arabic', models.CharField(max_length=100, verbose_name='Название (арабский)')),
                ('name_latin', models.CharField(max_length=100, verbose_name='Название (латиница)')),
                ('name_translation', models.CharField(max_length=200, verbose_name='Перевод названия')),
                ('revelation_type', models.CharField(max_length=20, verbose_name='Место ниспослания')),
                ('ayah_count', models.IntegerField(verbose_name='Количество аятов')),
            ],
            options={
                'verbose_name': 'Сура',
                'verbose_name_plural': 'Суры',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Ayah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер аята')),
                ('text_arabic', models.TextField(verbose_name='Текст (арабский)')),
                ('text_translation', models.TextField(blank=True, default='', verbose_name='Перевод')),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayahs', to='quran.surah')),
            ],
            options={
                'verbose_name': 'Аят',
                'verbose_name_plural': 'Аяты',
                'ordering': ['surah__number', 'number'],
                'unique_together': {('surah', 'number')},
            },
        ),
    ]
